# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  test-db:
    image: postgres:14
    restart: always
    container_name: integration-tests-db
    ports:
      - '5433:5432'
    env_file:
      - .env.test
    volumes:
      - ./pgdata:/var/lib/postgresql/data
