version: '3.8'

services:
  node_backend:
    container_name: node_backend
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    links:
      - db
    environment:
      - PGUSER=piperous
      - PGPASSWORD=123456
      - PGDATABASE=defaultdb
      - PGHOST=db
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    ports:
      - '${PORT}:${PORT}'
    command: npm run dev
  db:
    container_name: db
    image: 'postgres:14'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=piperous
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=defaultdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
