version: '3.8'

services:
  node_backend:
    container_name: node_backend
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    links:
      - postgres-db
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
      - /home/node/app/prisma
    ports:
      - '${PORT}:${PORT}'
    expose:
      - ${PORT}
    command: npm run dev
  prisma:
    container_name: prisma
    links:
      - postgres-db
    depends_on:
      - postgres-db
    ports:
      - '5555:5555'
    build:
      context: prisma
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - /home/node/app/prisma
  postgres-db:
    container_name: postgres-db
    image: 'postgres:14'
    restart: always
    env_file:
      - .env
    expose:
      - '5432'
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
volumes:
  postgres:
